In [2]:
import json
import pandas as pd
import MeCab

In [3]:
stories_json = []
with open('./output_storiesv3.json', 'r') as f:
    stories_json = stories_json + json.loads(f.read())

print(len(stories_json))
print(stories_json[1].keys())

529
dict_keys(['index', 'title', 'broadcasting_date', 'abstracts_list'])

In [4]:
stories_df = pd.DataFrame(stories_json)
stories_df["abstract_joined"] = stories_df["abstracts_list"].str.join(" ")
stories_df.head()

,index,title,broadcasting_date,abstracts_list,abstract_joined
0,0325,2013年3月15日放送,2013年3月15日,[何をやってもうまくいかないのび太は、「魔法（まほう）が使えたら便利で楽しくなるにちがいない...,何をやってもうまくいかないのび太は、「魔法（まほう）が使えたら便利で楽しくなるにちがいない」...
1,0326,2013年4月12日放送,2013年4月12日,[ある朝、ねぼうしたのび太に泣きつかれたドラえもんは、『ばくはつコショウ』を取り出す。このコ...,ある朝、ねぼうしたのび太に泣きつかれたドラえもんは、『ばくはつコショウ』を取り出す。このコシ...
2,0327,2013年4月26日放送,2013年4月26日,[スネ夫からハワイ旅行をじまんされたのび太は、自分もハワイに行きたいとママにたのもうとするが...,スネ夫からハワイ旅行をじまんされたのび太は、自分もハワイに行きたいとママにたのもうとするが、...
3,0328,2013年5月3日放送,2013年5月3日,[のび太とドラえもんが部屋で昼寝をしていると、突然大きな音が聞こえてくる。となりの家が改築工...,のび太とドラえもんが部屋で昼寝をしていると、突然大きな音が聞こえてくる。となりの家が改築工事...
4,0329,2013年5月10日放送,2013年5月10日,[そうじにせんたく、町内会の会合と毎日大忙しのママが、「体がもうひとつほしい」とため息をつい...,そうじにせんたく、町内会の会合と毎日大忙しのママが、「体がもうひとつほしい」とため息をついて...

In [5]:
t = MeCab.Tagger('-d /opt/homebrew/lib/mecab/dic/mecab-ipadic-neologd')
def mecab_tokenizer(text):
    parsed_lines = t.parse(text).split("\n")[:-2]
    surfaces = [l.split('\t')[0] for l in parsed_lines]
    features = [l.split('\t')[1] for l in parsed_lines]
    # 原型を取得
    bases = [f.split(',')[6] for f in features]
    # 品詞を取得
    pos = [f.split(',')[0] for f in features]

    # 各単語を原型に変換する
    token_list = [b if b != '*' else s for s, b in zip(surfaces, bases)]
    # 品詞を絞り込み
    target_pos = ["名詞"]
    token_list = [t for t, p in zip(token_list, pos) if p in target_pos]
    # アルファベットを小文字に統一
    token_list = [t.lower() for t in token_list]

    return [ text for text in filter(lambda x: not x.isascii(), token_list)]

wt = MeCab.Tagger('-Owakati')
def mecab_tokenizer_wakachi(text):
    return wt.parse(text).split(" ")

In [6]:
# ストーリーが取得できたものに絞る
stories_df = stories_df[stories_df['abstract_joined'].str.len() > 0] 
sentences = stories_df["abstract_joined"].apply(mecab_tokenizer).apply(set).apply(list)
print(sentences)
print(sentences)

0      [ドラえもん, 元, のび太, 異常気象, 大慌て, 演出, 満月, ため, 不器用, 何,...
1      [ドラえもん, 大騒ぎ, 話, 会社, のび太, 一生, 到着, 爆発, マイク, ラジコン...
2      [みごと, ドラえもん, 天女の舞, 最後, 節約レシピ, 相談, のび太, お金, それ,...
3      [ドラえもん, スイッチ, のび太, それ, 目, ジャイ子, 万能, ジャイアン, どくさ...
4      [満足, 有名, のび太, 撮影, 全身, 効率的, 歌手, タイムセール, ため息, 体,...
                             ...
524    [仮病, ドラえもん, よけい, 前日, のび太, 新品, 秘密, 用意, 手作り, 目, ...
525    [有名, 巣, のび太, お金, 年, 発見, ひみつ道具, カッコ, いつ, 道, きょう...
526    [マンガ, ドラえもん, ペン, のび太, ぼうし, コーディネート, ため, 反のう, 何...
527    [有名, のび太, 楽器, 交響楽, ひみつ道具, 音, うそ, 気, かな, 二人, 同情...
528    [マンガ, ドラえもん, ら, どこか, 名画, カンガルー, 話, のび太, おじさん, ...
Name: abstract_joined, Length: 529, dtype: object
0      [ドラえもん, 元, のび太, 異常気象, 大慌て, 演出, 満月, ため, 不器用, 何,...
1      [ドラえもん, 大騒ぎ, 話, 会社, のび太, 一生, 到着, 爆発, マイク, ラジコン...
2      [みごと, ドラえもん, 天女の舞, 最後, 節約レシピ, 相談, のび太, お金, それ,...
3      [ドラえもん, スイッチ, のび太, それ, 目, ジャイ子, 万能, ジャイアン, どくさ...
4      [満足, 有名, のび太, 撮影, 全身, 効率的, 歌手, タイムセール, ため息, 体,...
                             ...
524    [仮病, ドラえもん, よけい, 前日, のび太, 新品, 秘密, 用意, 手作り, 目, ...
525    [有名, 巣, のび太, お金, 年, 発見, ひみつ道具, カッコ, いつ, 道, きょう...
526    [マンガ, ドラえもん, ペン, のび太, ぼうし, コーディネート, ため, 反のう, 何...
527    [有名, のび太, 楽器, 交響楽, ひみつ道具, 音, うそ, 気, かな, 二人, 同情...
528    [マンガ, ドラえもん, ら, どこか, 名画, カンガルー, 話, のび太, おじさん, ...
Name: abstract_joined, Length: 529, dtype: object

In [7]:
print(stories_df[stories_df["abstract_joined"].str.contains("凶悪")]["abstract_joined"])

50    今日はドラえもんの誕生日。ドラえもんをおどろかせるようなものをプレゼントしたいと考えたのび太...
Name: abstract_joined, dtype: object

In [8]:
print(stories_df[stories_df["abstract_joined"].str.contains("学術研究")][["title", "abstract_joined"]])

           title                                    abstract_joined
81  2015年6月12日放送  以前、おばさんからもらったおこづかいを、貯金箱に入れて裏山にうめておいたのび太。自分で書いた...

In [9]:
keywords_dict = {}
for keyword_list in sentences.tolist():
    for keyword in keyword_list:
        if (keyword not in keywords_dict): keywords_dict[keyword] = 1
        else: keywords_dict[keyword] = keywords_dict[keyword] + 1

keywords_df = pd.DataFrame([{
    "key": key,
    "val": val
} for key,val in keywords_dict.items()])
keywords_df = keywords_df.sort_values("val", ascending=False)

In [10]:
pd.set_option('display.max_rows', 500)
keywords_df

          key  val
2         のび太  529
0       ドラえもん  528
30          の  505
95         こと  504
45        スネ夫  411
...       ...  ...
4379       友情    1
4380       はげ    1
4381       天地    1
4383  ぼくのロボット    1
7214     鳥獣戯画    1

[7215 rows x 2 columns]

In [11]:
keywords_df.to_csv('doraemon-word-frequencies.csv')

In [12]:
keywords_df.head()

      key  val
2     のび太  529
0   ドラえもん  528
30      の  505
95     こと  504
45    スネ夫  411

In [13]:
# CSVが「key,val」のフォーマットの場合、単語と出現数を取得
custom_word_counts = dict(zip(keywords_df["key"], keywords_df["val"]))

# 独自リストの総単語数
total_custom_count = sum(custom_word_counts.values())

# 確率分布を計算
custom_probabilities = {word: count / total_custom_count for word, count in custom_word_counts.items()}

In [14]:
print(custom_probabilities)

{'のび太': 0.012716346153846154, 'ドラえもん': 0.012692307692307692, 'の': 0.012139423076923077, 'こと': 0.012115384615384615, 'スネ夫': 0.009879807692307693, 'ジャイアン': 0.009591346153846153, 'ところ': 0.009350961538461539, 'よう': 0.008894230769230769, 'ママ': 0.008413461538461538, '中': 0.008317307692307692, 'しずか': 0.008245192307692308, '家': 0.008149038461538461, 'ため': 0.007932692307692307, 'ビックリ': 0.0076442307692307695, 'それ': 0.007596153846153846, '自分': 0.007307692307692308, 'たち': 0.0071875, 'その後': 0.006394230769230769, '部屋': 0.005745192307692308, 'もの': 0.0055769230769230765, 'これ': 0.0055769230769230765, '…。': 0.005360576923076923, 'ひみつ道具': 0.005216346153846154, 'みんな': 0.004951923076923077, '二人': 0.004879807692307692, '何': 0.004471153846153846, '人': 0.004447115384615384, '前': 0.004375, '大喜び': 0.004278846153846154, '手': 0.004206730769230769, 'パパ': 0.004134615384615385, 'ポケット': 0.003701923076923077, '１': 0.003629807692307692, '話': 0.003629807692307692, '空き地': 0.003269230769230769, 'そこ': 0.0032211538461538462, '様子': 0.003173076923076923, '外': 0.0031490384615384614, 'そう': 0.003076923076923077, '道具': 0.0030528846153846153, '後': 0.0029567307692307692, '０': 0.0029326923076923076, '目': 0.0028125, '上': 0.002716346153846154, '日': 0.0026201923076923078, '未来': 0.0026201923076923078, 'ん': 0.002596153846153846, '時': 0.002548076923076923, 'じまん': 0.0024759615384615384, '宿題': 0.002403846153846154, 'しかた': 0.0023557692307692307, '学校': 0.0022836538461538463, 'マンガ': 0.002235576923076923, 'まま': 0.002235576923076923, '庭': 0.002235576923076923, '２': 0.0022115384615384614, '声': 0.002139423076923077, '本': 0.0020673076923076925, '頭': 0.0020673076923076925, '遊び': 0.002043269230769231, 'バカ': 0.0020192307692307693, 'セット': 0.001971153846153846, '顔': 0.0019471153846153846, 'どら焼き': 0.0018990384615384616, '時間': 0.0018509615384615385, '体': 0.0018509615384615385, 'さん': 0.001826923076923077, 'テレビ': 0.001826923076923077, '一': 0.0018028846153846155, '気': 0.0017788461538461539, '帰宅': 0.0017548076923076922, '場所': 0.0017548076923076922, 'かん': 0.0017307692307692308, '３': 0.0017067307692307692, '大変': 0.0017067307692307692, 'ロボット': 0.0016826923076923078, '口': 0.0016826923076923078, 'さ': 0.0016346153846153845, '出木杉': 0.0016346153846153845, 'げん': 0.0016346153846153845, '今日': 0.0015865384615384615, 'がた': 0.0015625, 'きた': 0.0015625, '出し手': 0.0015384615384615385, '調子': 0.0014903846153846154, '５': 0.0014903846153846154, '本物': 0.0014663461538461538, '昼寝': 0.0014663461538461538, 'うち': 0.0014423076923076924, 'いっしょ': 0.0014423076923076924, 'しよう': 0.0014423076923076924, 'いろいろ': 0.0013942307692307691, '機': 0.0013942307692307691, '約束': 0.0013942307692307691, '野球': 0.0013701923076923077, '先生': 0.001346153846153846, 'ためし': 0.001346153846153846, 'もと': 0.0013221153846153847, '成功': 0.0013221153846153847, '年': 0.0013221153846153847, 'どこでもドア': 0.001298076923076923, 'だれ': 0.001298076923076923, '次': 0.001298076923076923, 'たくさん': 0.0012740384615384614, '発見': 0.00125, '勝手': 0.0012259615384615384, 'ちゅ': 0.0012259615384615384, '練習': 0.0012259615384615384, '相手': 0.0012259615384615384, 'どこ': 0.0011778846153846154, 'はず': 0.0011778846153846154, '家出': 0.0011778846153846154, '足': 0.0011778846153846154, '夜': 0.0011778846153846154, '今度': 0.001153846153846154, '写真': 0.001153846153846154, 'せい': 0.001153846153846154, '近く': 0.0011298076923076923, 'せん': 0.0011298076923076923, '水': 0.0011298076923076923, '直後': 0.0011298076923076923, '空': 0.0011298076923076923, 'テスト': 0.0011298076923076923, '山': 0.0011298076923076923, '分': 0.0011298076923076923, 'スイッチ': 0.0011057692307692307, 'ら': 0.0011057692307692307, '説明': 0.0010817307692307693, '元': 0.0010817307692307693, 'きょう': 0.0010817307692307693, 'おやつ': 0.0010817307692307693, '道': 0.0010817307692307693, 'おじさん': 0.0010817307692307693, '朝': 0.0010576923076923077, 'こづかい': 0.0010576923076923077, 'かわいそう': 0.0010576923076923077, '子ども': 0.0010576923076923077, '好き': 0.0010336538461538463, '間': 0.0010336538461538463, '公園': 0.0010336538461538463, 'ほう': 0.0010096153846153846, '大慌て': 0.0010096153846153846, '世界': 0.0010096153846153846, 'カン': 0.0010096153846153846, 'ボール': 0.0010096153846153846, 'ネコ': 0.0010096153846153846, '円': 0.000985576923076923, '言葉': 0.000985576923076923, '勉強': 0.000985576923076923, '完成': 0.0009615384615384616, '電話': 0.0009615384615384616, 'ほか': 0.0009615384615384616, 'カメラ': 0.0009615384615384616, '先': 0.0009615384615384616, 'ひとり': 0.0009615384615384616, 'ボタン': 0.0009375, '犬': 0.0009375, '変身': 0.0009375, '自分たち': 0.0009134615384615384, '心配': 0.0009134615384615384, 'プレゼント': 0.0009134615384615384, '形': 0.0009134615384615384, 'なん': 0.0009134615384615384, 'ドラミ': 0.0009134615384615384, 'ごと': 0.0009134615384615384, '点': 0.0008894230769230769, '宇宙': 0.0008894230769230769, 'ウソ': 0.0008894230769230769, '動物': 0.0008894230769230769, '力': 0.0008894230769230769, '姿': 0.0008894230769230769, 'しょう': 0.0008894230769230769, 'どこか': 0.0008653846153846154, '箱': 0.0008653846153846154, '雨': 0.0008653846153846154, 'ダメ': 0.0008413461538461539, '裏山': 0.0008413461538461539, 'じょう': 0.0008413461538461539, '地球': 0.0008413461538461539, 'ひとつ': 0.0008173076923076923, 'ボク': 0.0008173076923076923, '海': 0.0008173076923076923, '人間': 0.0008173076923076923, 'とき': 0.0008173076923076923, '４': 0.0008173076923076923, 'それぞれ': 0.0008173076923076923, '買い物': 0.0007932692307692307, '世紀': 0.0007932692307692307, 'ドア': 0.0007932692307692307, '通り': 0.0007932692307692307, 'あまり': 0.0007932692307692307, '心': 0.0007692307692307692, '途中': 0.0007692307692307692, '到着': 0.0007451923076923077, '音': 0.0007451923076923077, 'お金': 0.0007451923076923077, '帰り道': 0.0007451923076923077, '女の子': 0.0007451923076923077, 'ゲーム': 0.0007451923076923077, '提案': 0.0007451923076923077, '型': 0.0007451923076923077, '夢': 0.0007451923076923077, '方': 0.0007451923076923077, 'ころ': 0.0007451923076923077, '必死': 0.0007451923076923077, '近所': 0.0007211538461538462, '相談': 0.0007211538461538462, '出現': 0.0007211538461538462, '最新': 0.0007211538461538462, 'おもちゃ': 0.0007211538461538462, '反応': 0.0007211538461538462, '明日': 0.0007211538461538462, '周り': 0.0006971153846153846, '気持ち': 0.0006971153846153846, '毎日': 0.0006971153846153846, 'すべて': 0.0006971153846153846, '別': 0.0006971153846153846, '巨大': 0.0006971153846153846, '反対': 0.0006971153846153846, 'おなか': 0.0006971153846153846, 'ネズミ': 0.000673076923076923, 'ケンカ': 0.000673076923076923, '身': 0.000673076923076923, '一人': 0.000673076923076923, 'ある日': 0.000673076923076923, '宣言': 0.0006490384615384615, 'タケコプター': 0.0006490384615384615, '友だち': 0.0006490384615384615, '出発': 0.000625, '絵': 0.000625, '星': 0.000625, '町': 0.000625, 'しゅん': 0.000625, '野比': 0.000625, 'じゅう': 0.000625, '無事': 0.000625, '人気': 0.000625, '映像': 0.000625, '鼻': 0.000625, 'いま': 0.000625, '用': 0.000625, '移動': 0.0006009615384615385, 'い': 0.0006009615384615385, '助け': 0.0006009615384615385, 'わけ': 0.0006009615384615385, '子供達': 0.0006009615384615385, '説教': 0.0006009615384615385, '時代': 0.0006009615384615385, '名前': 0.0006009615384615385, 'す': 0.0006009615384615385, '瞬間': 0.0006009615384615385, 'ぼう': 0.0006009615384615385, '木': 0.0006009615384615385, '日本': 0.000576923076923077, '屋根': 0.000576923076923077, '窓': 0.000576923076923077, 'ゅう': 0.000576923076923077, '裏': 0.000576923076923077, '試合': 0.000576923076923077, 'ふしぎ': 0.000576923076923077, '参加': 0.000576923076923077, '感動': 0.000576923076923077, 'ペット': 0.000576923076923077, '急': 0.000576923076923077, 'スモールライト': 0.0005528846153846154, '空間': 0.0005528846153846154, '地面': 0.0005528846153846154, 'あと': 0.0005528846153846154, 'タイム': 0.0005528846153846154, '誰か': 0.0005528846153846154, 'たん': 0.0005528846153846154, '紙': 0.0005528846153846154, '風': 0.0005528846153846154, '注意': 0.0005528846153846154, 'とたん': 0.0005288461538461538, 'いたずら': 0.0005288461538461538, '気分': 0.0005288461538461538, '帰り': 0.0005288461538461538, '逃げ': 0.0005288461538461538, '物': 0.0005288461538461538, '今': 0.0005288461538461538, 'つくえ': 0.0005288461538461538, 'みたい': 0.0005288461538461538, '決意': 0.0005288461538461538, 'デパート': 0.0005288461538461538, 'ペン': 0.0005288461538461538, '大激怒': 0.0005288461538461538, '描': 0.0005288461538461538, '度': 0.0005288461538461538, '回': 0.0005048076923076923, '高級': 0.0005048076923076923, 'ふり': 0.0005048076923076923, '結局': 0.0005048076923076923, 'すき': 0.0005048076923076923, 'ガス': 0.0005048076923076923, '夏休み': 0.0005048076923076923, '大笑い': 0.0005048076923076923, 'モノ': 0.0005048076923076923, 'トイレ': 0.0005048076923076923, '野郎': 0.0005048076923076923, 'ケーキ': 0.0005048076923076923, 'おかげ': 0.0005048076923076923, 'あちこち': 0.0004807692307692308, '６': 0.0004807692307692308, '誕生日': 0.0004807692307692308, 'さまざま': 0.0004807692307692308, '店': 0.0004807692307692308, '場': 0.0004807692307692308, 'お願い': 0.0004807692307692308, 'ちがい': 0.0004807692307692308, '花': 0.0004807692307692308, '楽しみ': 0.0004807692307692308, '激怒': 0.0004807692307692308, '夢中': 0.0004807692307692308, '味': 0.0004807692307692308, '満足': 0.0004807692307692308, 'ミニ': 0.0004807692307692308, '仕事': 0.0004807692307692308, '雲': 0.0004807692307692308, '階段': 0.0004807692307692308, 'そうじ': 0.0004807692307692308, 'かた': 0.0004807692307692308, '方法': 0.0004807692307692308, 'ゴミ': 0.0004807692307692308, '代わり': 0.0004567307692307692, '少年': 0.0004567307692307692, '魚': 0.0004567307692307692, '簡単': 0.0004567307692307692, 'えいぞう': 0.0004567307692307692, '使い': 0.0004567307692307692, 'くん': 0.0004567307692307692, '安心': 0.0004567307692307692, 'ごっこ': 0.0004567307692307692, '人物': 0.0004567307692307692, '大騒ぎ': 0.0004567307692307692, 'ただ': 0.0004567307692307692, 'いつ': 0.0004567307692307692, '自由': 0.0004567307692307692, '誰': 0.0004567307692307692, '万': 0.0004567307692307692, '必要': 0.0004567307692307692, '昔': 0.0004567307692307692, 'じゃま': 0.0004326923076923077, 'まんぞく': 0.0004326923076923077, '景色': 0.0004326923076923077, '撃': 0.0004326923076923077, '願い': 0.0004326923076923077, '仕返し': 0.0004326923076923077, '神成': 0.0004326923076923077, '人形': 0.0004326923076923077, '撮影': 0.0004326923076923077, '感心': 0.0004326923076923077, '別荘': 0.0004326923076923077, 'げき': 0.0004326923076923077, '用意': 0.0004326923076923077, '最後': 0.0004326923076923077, 'カード': 0.0004326923076923077, '確認': 0.0004326923076923077, '川': 0.0004326923076923077, 'シール': 0.0004326923076923077, '雪': 0.0004326923076923077, '部分': 0.00040865384615384613, '今年': 0.00040865384615384613, 'ロープ': 0.00040865384615384613, 'とおり': 0.00040865384615384613, '効果': 0.00040865384615384613, '料理': 0.00040865384615384613, '一方': 0.00040865384615384613, 'どれ': 0.00040865384615384613, '同情': 0.00040865384615384613, 'ぼく': 0.00040865384615384613, 'ぶり': 0.00040865384615384613, '男': 0.00040865384615384613, 'ボロボロ': 0.00040865384615384613, '注文': 0.00040865384615384613, '命令': 0.00040865384615384613, 'かく': 0.00040865384615384613, '車': 0.00040865384615384613, 'ちゃん': 0.00040865384615384613, '元気': 0.00040865384615384613, '使い方': 0.00040865384615384613, '最初': 0.00040865384615384613, '島': 0.00040865384615384613, '準備': 0.00040865384615384613, '旅行': 0.00040865384615384613, '的': 0.0003846153846153846, '失敗': 0.0003846153846153846, '末': 0.0003846153846153846, '感謝': 0.0003846153846153846, 'ここ': 0.0003846153846153846, '何とか': 0.0003846153846153846, '草むしり': 0.0003846153846153846, '空気': 0.0003846153846153846, '玉': 0.0003846153846153846, '服': 0.0003846153846153846, 'こ': 0.0003846153846153846, '翌日': 0.0003846153846153846, 'タイムふろしき': 0.0003846153846153846, 'あな': 0.0003846153846153846, '大好き': 0.0003605769230769231, '雑誌': 0.0003605769230769231, '腹': 0.0003605769230769231, 'スネ夫のママ': 0.0003605769230769231, '光': 0.0003605769230769231, '鏡': 0.0003605769230769231, '飛行機': 0.0003605769230769231, 'つり': 0.0003605769230769231, '家族': 0.0003605769230769231, '全部': 0.0003605769230769231, '歌': 0.0003605769230769231, '机': 0.0003605769230769231, '協力': 0.0003605769230769231, '物置': 0.0003605769230769231, 'ろ': 0.0003605769230769231, 'アイドル': 0.0003605769230769231, '化': 0.0003605769230769231, 'び': 0.0003605769230769231, '世話': 0.0003605769230769231, 'おかし': 0.0003605769230769231, '名': 0.0003605769230769231, '時計': 0.0003605769230769231, 'エサ': 0.0003605769230769231, 'した': 0.0003605769230769231, 'ダイヤル': 0.0003605769230769231, '自動': 0.0003605769230769231, '最近': 0.0003605769230769231, 'だい': 0.0003605769230769231, '本当': 0.0003605769230769231, '持ち主': 0.0003605769230769231, '笑顔': 0.0003605769230769231, '舞台': 0.0003365384615384615, '地図': 0.0003365384615384615, 'げ': 0.0003365384615384615, 'ロケット': 0.0003365384615384615, 'ジュース': 0.0003365384615384615, 'ろう': 0.0003365384615384615, 'チーム': 0.0003365384615384615, '操作': 0.0003365384615384615, 'モニター': 0.0003365384615384615, 'おじいさん': 0.0003365384615384615, 'うつ': 0.0003365384615384615, '設定': 0.0003365384615384615, 'テーブル': 0.0003365384615384615, '観察': 0.0003365384615384615, '下': 0.0003365384615384615, 'となり': 0.0003365384615384615, 'スタート': 0.0003365384615384615, '船': 0.0003365384615384615, '誕生': 0.0003365384615384615, 'ランドセル': 0.0003365384615384615, '誘い': 0.0003365384615384615, 'きん': 0.0003365384615384615, '子': 0.0003365384615384615, '屋': 0.0003365384615384615, '直前': 0.0003365384615384615, 'スプレー': 0.0003365384615384615, 'しん': 0.0003365384615384615, 'マイク': 0.0003365384615384615, '不安': 0.0003365384615384615, '石': 0.0003365384615384615, '式': 0.0003365384615384615, '自転車': 0.0003365384615384615, 'さっき': 0.0003365384615384615, '目的地': 0.0003365384615384615, 'にも': 0.0003365384615384615, '後ろ': 0.0003365384615384615, '映画': 0.0003365384615384615, 'えい': 0.0003125, '返事': 0.0003125, '大会': 0.0003125, '時機': 0.0003125, 'どちら': 0.0003125, 'かわり': 0.0003125, '会社': 0.0003125, '設置': 0.0003125, '本人': 0.0003125, '現代': 0.0003125, '機械': 0.0003125, 'きれい': 0.0003125, '千': 0.0003125, '商品': 0.0003125, '予定': 0.0003125, '上手': 0.0003125, '大切': 0.0003125, '理由': 0.0003125, '大人': 0.0003125, 'いない': 0.0003125, '押し入れ': 0.0003125, 'リモコン': 0.0003125, '結果': 0.0003125, 'イヤ': 0.0003125, '開始': 0.0003125, '８': 0.0003125, 'っぱなし': 0.0003125, 'つもり': 0.0003125, '犯人': 0.0003125, '答え': 0.0003125, '対決': 0.0003125, '将来': 0.0003125, '手紙': 0.0003125, 'クラスメイト': 0.0003125, '大事': 0.0003125, 'タマゴ': 0.0003125, 'ナゾ': 0.0002884615384615385, 'ページ': 0.0002884615384615385, '電気': 0.0002884615384615385, '寝坊': 0.0002884615384615385, '最高': 0.0002884615384615385, 'はじめ': 0.0002884615384615385, '一緒': 0.0002884615384615385, '番組': 0.0002884615384615385, '興味': 0.0002884615384615385, '引き出し': 0.0002884615384615385, '教室': 0.0002884615384615385, '計画': 0.0002884615384615385, '二つ': 0.0002884615384615385, '整理': 0.0002884615384615385, 'やる気': 0.0002884615384615385, '客': 0.0002884615384615385, '三': 0.0002884615384615385, '体験': 0.0002884615384615385, 'お礼': 0.0002884615384615385, '肩': 0.0002884615384615385, '仲間': 0.0002884615384615385, '一緒に': 0.0002884615384615385, '赤ちゃん': 0.0002884615384615385, '土管': 0.0002884615384615385, 'だらけ': 0.0002884615384615385, '便利': 0.0002884615384615385, '玄関': 0.0002884615384615385, '仲間外れ': 0.0002884615384615385, '自動的': 0.0002884615384615385, 'オモチャ': 0.0002884615384615385, '勝負': 0.0002884615384615385, 'ラジコン': 0.0002884615384615385, '用事': 0.0002884615384615385, '落下': 0.0002884615384615385, '本屋': 0.0002884615384615385, 'じゅん': 0.0002884615384615385, 'メガネ': 0.0002884615384615385, 'スーパー': 0.0002884615384615385, '夫': 0.0002884615384615385, 'お年玉': 0.0002884615384615385, '発売': 0.0002884615384615385, '昨日': 0.0002884615384615385, '町内': 0.0002884615384615385, '９': 0.0002884615384615385, 'ハウス': 0.0002884615384615385, 'かい': 0.0002884615384615385, '作り': 0.0002884615384615385, '立体': 0.0002884615384615385, '生物': 0.0002884615384615385, '状態': 0.0002884615384615385, '階': 0.0002884615384615385, 'こうか': 0.0002884615384615385, 'タヌキ': 0.0002884615384615385, 'ジャイ子': 0.0002884615384615385, '仕組み': 0.0002884615384615385, 'ガラス': 0.0002884615384615385, 'さい': 0.0002884615384615385, '植物': 0.0002884615384615385, 'カベ': 0.0002884615384615385, '秘密': 0.0002884615384615385, '帰ってきたドラえもん': 0.0002884615384615385, '仕方がない': 0.0002644230769230769, 'ヒーロー': 0.0002644230769230769, '生き物': 0.0002644230769230769, '材料': 0.0002644230769230769, '紹介': 0.0002644230769230769, 'リサイタル': 0.0002644230769230769, '入ろう': 0.0002644230769230769, 'ライト': 0.0002644230769230769, '７': 0.0002644230769230769, 'チケット': 0.0002644230769230769, 'カゴ': 0.0002644230769230769, '呼び出し': 0.0002644230769230769, '特別': 0.0002644230769230769, '新作': 0.0002644230769230769, 'せき': 0.0002644230769230769, '図鑑': 0.0002644230769230769, 'ぼうし': 0.0002644230769230769, '実験': 0.0002644230769230769, 'セワシ': 0.0002644230769230769, 'ぎ': 0.0002644230769230769, 'ごちそう': 0.0002644230769230769, 'かけ': 0.0002644230769230769, '成長': 0.0002644230769230769, '種類': 0.0002644230769230769, '問題': 0.0002644230769230769, '池': 0.0002644230769230769, '何度': 0.0002644230769230769, '横': 0.0002644230769230769, '土': 0.0002644230769230769, '冬': 0.0002644230769230769, 'プラモデル': 0.0002644230769230769, '台所': 0.0002644230769230769, '倍': 0.0002644230769230769, 'カサ': 0.0002644230769230769, '大冒険': 0.0002644230769230769, '冒険': 0.0002644230769230769, '山奥': 0.0002644230769230769, 'ちょう': 0.0002644230769230769, '見事': 0.0002644230769230769, '男の子': 0.0002644230769230769, 'コピー': 0.0002644230769230769, 'アドバイス': 0.0002644230769230769, 'はんのう': 0.0002644230769230769, '決心': 0.0002644230769230769, '仕方': 0.0002644230769230769, 'ため息': 0.0002644230769230769, '月': 0.0002403846153846154, '宝': 0.0002403846153846154, '正体': 0.0002403846153846154, '生活': 0.0002403846153846154, '悪いこと': 0.0002403846153846154, 'ボックス': 0.0002403846153846154, '彼ら': 0.0002403846153846154, '放題': 0.0002403846153846154, 'たんじょう': 0.0002403846153846154, '操縦': 0.0002403846153846154, '粒': 0.0002403846153846154, '以上': 0.0002403846153846154, '遠く': 0.0002403846153846154, 'ムリ': 0.0002403846153846154, '忘れ物': 0.0002403846153846154, 'ボコボコ': 0.0002403846153846154, 'ポスト': 0.0002403846153846154, '修理': 0.0002403846153846154, '音楽': 0.0002403846153846154, '自信': 0.0002403846153846154, '弾': 0.0002403846153846154, '世界中': 0.0002403846153846154, '居間': 0.0002403846153846154, 'ショック': 0.0002403846153846154, 'パーティー': 0.0002403846153846154, '太': 0.0002403846153846154, 'いとこ': 0.0002403846153846154, '記録': 0.0002403846153846154, '寒さ': 0.0002403846153846154, '続き': 0.0002403846153846154, '小鳥': 0.0002403846153846154, '結婚': 0.0002403846153846154, '糸': 0.0002403846153846154, '穴': 0.0002403846153846154, 'しない': 0.0002403846153846154, 'みごと': 0.0002403846153846154, '以外': 0.0002403846153846154, '強引': 0.0002403846153846154, 'いつものように': 0.0002403846153846154, '思い': 0.0002403846153846154, '戦い': 0.0002403846153846154, '引っ越し': 0.0002403846153846154, '中止': 0.0002403846153846154, 'いっぱい': 0.0002403846153846154, 'サイズ': 0.0002403846153846154, 'ご飯': 0.0002403846153846154, '利上げ': 0.0002403846153846154, '風呂': 0.0002403846153846154, '数': 0.0002403846153846154, '食べ物': 0.0002403846153846154, '改造': 0.0002403846153846154, '空中': 0.0002403846153846154, 'クリーム': 0.0002403846153846154, '利用': 0.0002403846153846154, '城': 0.0002403846153846154, 'ママと': 0.0002403846153846154, 'おしり': 0.0002403846153846154, '輪': 0.0002403846153846154, '留守': 0.0002403846153846154, 'それら': 0.0002403846153846154, '方向': 0.0002403846153846154, 'ピーちゃん': 0.0002403846153846154, '画面': 0.0002403846153846154, 'しゅう': 0.0002403846153846154, '変化': 0.0002403846153846154, '時空': 0.0002403846153846154, 'カンタン': 0.0002403846153846154, 'キミ': 0.0002403846153846154, '有名': 0.0002403846153846154, '翌朝': 0.0002403846153846154, '連発': 0.0002403846153846154, 'せんたく': 0.0002403846153846154, 'ノート': 0.0002403846153846154, 'いちばん': 0.0002403846153846154, '四次元ポケット': 0.0002403846153846154, '天井': 0.0002403846153846154, '動き': 0.00021634615384615385, '押': 0.00021634615384615385, '答案用紙': 0.00021634615384615385, '片付け': 0.00021634615384615385, 'たび': 0.00021634615384615385, '表情': 0.00021634615384615385, '恐怖': 0.00021634615384615385, 'キット': 0.00021634615384615385, 'スペア': 0.00021634615384615385, 'きれいな': 0.00021634615384615385, 'ガリバートンネル': 0.00021634615384615385, '宝探し': 0.00021634615384615385, 'チラシ': 0.00021634615384615385, 'ステッキ': 0.00021634615384615385, '恐竜': 0.00021634615384615385, '発生': 0.00021634615384615385, '悪意': 0.00021634615384615385, '反論': 0.00021634615384615385, '専用': 0.00021634615384615385, '二': 0.00021634615384615385, '棒': 0.00021634615384615385, 'くつ': 0.00021634615384615385, '風船': 0.0

In [20]:
!pip install faker

Collecting faker
  Downloading faker-37.0.2-py3-none-any.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 3.6 MB/s eta 0:00:00a 0:00:01
Collecting tzdata
  Downloading tzdata-2025.1-py2.py3-none-any.whl (346 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.8/346.8 kB 4.6 MB/s eta 0:00:0000:0100:01
Installing collected packages: tzdata, faker
Successfully installed faker-37.0.2 tzdata-2025.1

[notice] A new release of pip is available: 23.0 -> 25.0.1
[notice] To update, run: pip install --upgrade pip

In [21]:
from faker import Faker

fake = Faker("ja_JP")

# ランダムな日本語の文章を5つ生成
sample_text = "\n".join([fake.text() for _ in range(5)])
print(sample_text)

協力リハビリ自体ブランチブレーキ索引。追放する器官創傷電池。戦略的ない埋め込む主婦は特徴。
サワー虐待舗装革新販売普通の。午前目的コーナー君は。サンプル持ってる動物ジャーナル転倒本質的な。
本質的な行進ジャム。トス織るリハビリ。
コミュニケーションコーナー索引符号チーズスキームバケツ憲法。怒り部隊屋根裏職人シュガートレーナー。合計ベルベット追放する陶器月。
催眠術感謝する創傷リニアスキーム。ブレーキタワー見出し戦略的。特徴コミュニケーション知覚差別する立派なトレーナーブレーキ。
尊敬する教会バーゲン。トースト陶器スペル明らかにする。行進合計テントバケツ主人シェービング行進革新。移動評議会花嫁私ジャム私バス。
バナー埋め込む参加するブランチカラム画面不自然な。器官不自然な葉敵敵対的な学生。
分割革新必要コミュニティテント立派な。錯覚数字風景葉ノートヒット。文言式フェミニスト試してみる今日。
評議会近代化する知覚トス出演者溝。索引あなた自身パンない。カレッジ虐待呼ぶ彼憲法日曜日偏差。
見落とすあなた自身運部隊反射クルー埋め込む。創傷残るハンマークルー販売文言舗装。脊椎品質細かい状況チーズ持つ鉱山。
プラスチック賞賛する花嫁戦略的君は明らかにするブラケット。パーセント式改善尊敬する。
主婦特徴特徴ストレージ転倒敵対的な。虐待残るデフォルトコミュニティ楽しんでチーズ。
織る雪カレッジ見落とすトースト楽しんで。トレーナー供給ヒール主人叔父トースト奨励します。ストレージ錯覚欠乏教会ハンマートリビュートスキーム。
ブレーキ倫理軸ダニ残るダイヤモンド。雪コーナー持っていましたピッククールバスケット。
尊敬する動物コーラス奨励します再現する。ベルベットシェービング犯罪者意図敵対的なタワー建築。
埋め込むパイオニア本質的なコミュニティブレーキインチ血まみれの私。持つ省略シュガー状況運シェービング分割。証言する君はささやきあったコミュニケーションノート。